blank_issues_enabled: false
contact_links:
  - name: Want to discuss anything else?
    url: https://github.com/sunnydsouza/sample-repo-github-actions/discussions/new
    about: Create a discussion about it.